services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: kaiser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

    restart: always